### ISSUE TITLE
question for id

### ISSUE THREAD

**Issue by adodo0829** [garrettbland/vue-google-ad-manager#1]
it seems thiat this.id && this.$googlead.id  should be in reverse

my google ad code demo:
 googletag.defineSlot('/21669498964/vfhy-xl/300x250-vip-xl-vfhy',  [300,  250],  'div-gpt-ad-1572329527477-0').addService(googletag.pubads());

yours: 
defineSlot(){
         googletag.defineSlot(this.adUnit, 
    this.sizes,this.id).defineSizeMapping(this.mapping).addService(googletag.pubads());
            },

**Comment by adodo0829** [comment]
fix it

**Comment by beshoo** [comment]
How you fixed it, and is this still works.?
